# Generated by Django 5.2.8 on 2025-12-04 02:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultoMayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Formato: 12345678-9', max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(9, 'El RUT debe tener al menos 9 caracteres'), django.core.validators.RegexValidator(message='Formato de RUT inválido. Ejemplo: 12345678-9', regex='^\\d{7,8}-[\\dkK]$')], verbose_name='RUT')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('direccion', models.TextField(verbose_name='Dirección de Residencia')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono de Contacto')),
                ('contacto_emergencia', models.CharField(blank=True, help_text='Nombre y teléfono del contacto de emergencia', max_length=200, null=True, verbose_name='Contacto de Emergencia')),
                ('observaciones_medicas', models.TextField(blank=True, help_text='Información médica relevante para los voluntarios', null=True, verbose_name='Observaciones Médicas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el adulto mayor está activo en el sistema', verbose_name='Beneficiario Activo')),
            ],
            options={
                'verbose_name': 'Adulto Mayor',
                'verbose_name_plural': 'Adultos Mayores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('SOLICITANTE', 'Solicitante - Jefe Junta Vecinos'), ('VOLUNTARIO', 'Voluntario - Pastoral Universitaria')], help_text='Define si el usuario es Solicitante o Voluntario', max_length=15, verbose_name='Rol del Usuario')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono de Contacto')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el usuario está activo en el sistema', verbose_name='Usuario Activo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_registro'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Solicitud')),
                ('descripcion', models.TextField(help_text='Describa la ayuda que necesita el adulto mayor', verbose_name='Descripción Detallada')),
                ('tipo_ayuda', models.CharField(help_text='Ej: Compras, Trámites, Compañía, Traslados, etc.', max_length=100, verbose_name='Tipo de Ayuda')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADA', 'Asignada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=15, verbose_name='Estado de la Solicitud')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Última Actualización')),
                ('fecha_limite', models.DateField(blank=True, help_text='Fecha en la que se necesita la ayuda', null=True, verbose_name='Fecha Límite')),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('comentarios_finalizacion', models.TextField(blank=True, help_text='Comentarios al finalizar la solicitud', null=True, verbose_name='Comentarios de Finalización')),
                ('adulto_mayor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='adultomayor.adultomayor', verbose_name='Adulto Mayor Beneficiario')),
                ('creador', models.ForeignKey(help_text='Usuario Solicitante que crea la solicitud', limit_choices_to={'rol': 'SOLICITANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creador de la Solicitud')),
                ('voluntario_asignado', models.ForeignKey(blank=True, limit_choices_to={'rol': 'VOLUNTARIO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Voluntario Asignado')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido del Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('leido', models.BooleanField(default=False, help_text='Indica si el mensaje ha sido leído por el destinatario', verbose_name='Mensaje Leído')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='adultomayor.solicitud', verbose_name='Solicitud Relacionada')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_postulacion', models.TextField(help_text='Mensaje del voluntario explicando por qué desea ayudar', verbose_name='Mensaje de Postulación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15, verbose_name='Estado de la Postulación')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Postulación')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Respuesta')),
                ('comentario_respuesta', models.TextField(blank=True, help_text='Comentario del solicitante al aceptar o rechazar', null=True, verbose_name='Comentario de Respuesta')),
                ('voluntario', models.ForeignKey(limit_choices_to={'rol': 'VOLUNTARIO'}, on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to=settings.AUTH_USER_MODEL, verbose_name='Voluntario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='adultomayor.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-fecha_postulacion'],
                'unique_together': {('voluntario', 'solicitud')},
            },
        ),
    ]
