# Generated by Django 5.2.7 on 2025-12-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adultomayor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cantidad_beneficiarios',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cantidad_presidentes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cantidad_voluntarios',
            field=models.IntegerField(default=1),
        ),
    ]
