# Generated by Django 5.2.7 on 2025-12-04 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adultomayor', '0002_solicitud_cantidad_beneficiarios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='adulto_mayor',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='voluntario',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='adultos_mayores',
            field=models.ManyToManyField(blank=True, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='voluntarios',
            field=models.ManyToManyField(blank=True, related_name='solicitudes_voluntariado', to=settings.AUTH_USER_MODEL),
        ),
    ]
